### ISSUE TITLE
Enhance Backup Upload Functionality: Return URL, File Size, and Timestamp after Upload to Cloud Storage

### ISSUE THREAD

**Issue by denisakp** [denisakp/sentinel#47]
### Description

Currently, when a backup is uploaded to cloud storage (e.g., S3, Google Cloud Storage, Azure Blobs), the system only prints a success message. This enhancement aims to extend the functionality by providing additional information after a successful upload, including:

- URL of the uploaded file.
- File size (in bytes).
- Timestamp of when the backup was completed.

These changes are crucial for improving traceability, automation, and error handling.

### Why This Change is Necessary 💡 

1. Traceability:

Returning the URL of the uploaded file helps users quickly locate the backup in the cloud storage. In case of any future data recovery or audits, knowing the exact location of the backup file is essential.

2. Automation:

Many CI/CD pipelines and automated systems rely on accurate metadata to trigger subsequent tasks. By providing the file size and timestamp, we enable better integration with monitoring tools, scripts, or third-party applications that might need this information for further processing.

3. Error Handling & Debugging:

In case of issues or discrepancies during the backup process, having access to the file URL, size, and timestamp can help in diagnosing problems faster. For instance, if a backup file is missing or corrupted, these details can quickly verify whether the upload was completed correctly.

### 📝 Acceptance Criteria

After a successful upload to cloud storage, the system should return:

- Full URL to the uploaded backup file.
- Size of the file in bytes.
- Timestamp of when the backup was uploaded.

The new output format should look like this:

```text
Backup uploaded successfully!
URL: https://mybucket.s3.amazonaws.com/backups/mybackup.tar.gz
File size: 50MB
Timestamp: 2024-11-18T10:30:00Z
```

### Tasks 🛠️ 

- [x] Update S3 upload handler to return URL, file size, and timestamp.
- [x] Implement similar updates for Google Cloud Storage and Azure Blob Storage handlers.
- [x] Update unit tests to validate the output format.
- [x]  Update the documentation to reflect the new output.
- [x] Perform end-to-end testing to verify the functionality in real cloud environments.
